### PR TITLE
Removed excess of consoles

### PR DESCRIPTION
**Pull request by ShyamBhalodiya**
There are three **consoles** in the file named *sketch.js* which may create problem for users.
Please accept this pull request so that the users can have better experience

### CODE REVIEW

**Comment by ShyamBhalodiya** [comment]
Please accept this pull request

**Comment by KaranAggarwal2008** [comment]
How to accept this pull request

**Review by KaranAggarwal2008 — COMMENTED** [review]
How to accept this pull request?

**Comment by KaranAggarwal2008** [comment]
Okay

**Comment by KaranAggarwal2008** [comment]
Hi whitehatjr/AngryBirdsStage2.5StudentActivity,

I have decided to fundraise for a cause that I passionately feel about. I
need your support to help me reach my target. Please contribute whatever
you can and be a part of this change.

false

Contributing through GiveIndia is easy, safe and you can rest assured that
the amount will reach the beneficiary NGO directly.

You will also be getting income tax benefits under section 80G for this
donation

**Pull request closed without merging**
